id: A958B19B8
title: f0C08
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 16:26:59.421201
  last_modified_at: 2022-05-27 16:26:59.421207
