id: A958B19B8
title: fCE92
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 16:26:59.929563
  last_modified_at: 2022-05-27 16:26:59.929566
