id: A958B19B8
title: fFAF1
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 16:27:00.029289
  last_modified_at: 2022-05-27 16:27:00.029294
